### ISSUE TITLE
Predict.py does not predict

### ISSUE THREAD

**Issue by rpkarandev** [luo-group/PenLight#1]
I am trying to run your model for my dataset (formatted in JSON) as per the instruction. However, the predict.py script does not predict instead just outputs from a stored list. The output and input ids are totally different. Please clarify is something wrong here.

**Comment by luojq19** [comment]
Hello. Sorry for the mistakes in predict.py. I have updated the predict.py as well as the README. Please try again to see if it solved your problem. Since PenLight is a contrastive learning method, so before prediction it needs to generate an embedding for each test protein, you could refer to the file src/results.py to generate the embeddings. Note that because PenLight used pretrained protein language models, so you also need to generate ESM-1b (for EC number) or ProtT5 (for cath prediction) embeddings and store them in a .h5 file, which would be used for inference. 
ESM repo link: https://github.com/facebookresearch/esm.git
ProtT5 repo link: https://github.com/agemagician/ProtTrans
Both the language model repos have very handy ways to generate embeddings from a given fasta file.
Hope this could solve your problem. If there's anything else you need just comment here or send emails to luojiaqi2019@gmail.com

**Comment by rpkarandev** [comment]
Thank you for your response! 

Just one more request: please record/list the ESM and ProtT5 versions you used to generate the existing lookup.pt in Readme.md file. It would be helpful.

**Comment by luojq19** [comment]
For CATH prediction, we used ProtT5-XL-UniRef50 (also ProtT5-XL-U50)
For EC number prediction, we used ESM-1b (esm1b_t33_650M_UR50S)

**Comment by rpkarandev** [comment]
thanks! I was able to calculate the ESM and ProtT5 embeddings. But I ended up with another issue while running the model.single  pass on the graphs. I will try to debug it. I am closing this issue.

**Comment by luojq19** [comment]
The current model checkpoints are trained on multiple gpus, so the models were wrapped with pytorch data.parallel. So to call the single_pass function you need to use model.module.single_pass
