### ISSUE TITLE
how to run preditc.py

### ISSUE THREAD

**Issue by myngsk** [luo-group/PenLight#2]
Hello. I have a question.
I want to do an enzyme number prediction and I have unlabeled data.
I have created an embedding and prepared an .h5 file.
I have checked the results.py but I am not sure how exactly to run it after this.

I would be grateful if you could tell me.

**Comment by myngsk** [comment]
I have checked the contents of resulsts.py and tried everything, but I cannot figure out how to create an embedded .pt file.
I have the protein Json data and the amino acid sequence embedding.h5 file.
It is a very interesting program that I would like to use.
I would appreciate it if you could tell me exactly how to create it.

**Comment by myngsk** [comment]
I was able to successfully process the EC number prediction. Thank you.
Please enlighten me on two things.
(1) I used extract.py to create the amino acid sequence embedding, what options (--repr_layers and --include) did you use?
https://github.com/facebookresearch/esm.git
(2) I got an error that the number of channels was not correct when I used the embedding as is (embedding is 1280, but 1286 is needed), so I padded it with zeros to align it to 1286, is this the way to do it?

**Comment by luojq19** [comment]
Hello! For the two questions:
(1) I used options `python extract.py esm1b_t33_650M_UR50S input.fasta out_dir/ --include per_tok` to generate ESM-1b embeddings.
(2) Sorry for the inconvenience. The 6 other channels are actually some scalar features from geometric vector perception (https://github.com/lucidrains/geometric-vector-perceptron). You can set the parameter concat=True in class GATModel to concatenate the 6 features to the embeddings. I include these features because the performance is slightly better.

**Comment by myngsk** [comment]
Thanks for your reply!
I did exactly as you said and got the expected results.

The case has been resolved.
